#!/bin/bash
# Setup script for Raspberry Pi running Ubuntu 25.10 ARM 64-bit
# This installs all system dependencies needed for the scanner nodes
# Can auto-configure server IP based on setup type

echo "======================================"
echo "Ubuntu 25.10 ARM64 Setup for Scanner Node"
echo "======================================"
echo ""

# Ask user about setup type
echo "Setup Type:"
echo "  1) Client only (will connect to remote server)"
echo "  2) Server + Client (this Pi runs both)"
echo ""
read -p "Choose setup type (1 or 2): " SETUP_TYPE
echo ""

if [[ "$SETUP_TYPE" == "2" ]]; then
    SERVER_IP="localhost"
    IS_SERVER_NODE=true
    echo "Selected: Server + Client setup"
    echo "Server will run on this Pi, client will connect to localhost"
elif [[ "$SETUP_TYPE" == "1" ]]; then
    IS_SERVER_NODE=false
    echo "Selected: Client only setup"
    echo "This Pi will connect to a remote server"
    echo ""
    read -p "Enter server IP address (e.g., 192.168.1.100): " SERVER_IP
    if [[ -z "$SERVER_IP" ]]; then
        echo "Error: Server IP is required"
        exit 1
    fi
else
    echo "Invalid choice. Exiting."
    exit 1
fi

echo ""
read -p "Which node is this? (1, 2, 3, etc.): " NODE_NUM
if [[ -z "$NODE_NUM" ]]; then
    echo "Error: Node number is required"
    exit 1
fi

echo ""

# Check if running Ubuntu
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "$ID" != "ubuntu" ]]; then
        echo "Warning: This script is designed for Ubuntu 25.10 ARM64"
        read -p "Continue anyway? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
    
    # Check architecture
    ARCH=$(uname -m)
    if [[ "$ARCH" != "aarch64" ]] && [[ "$ARCH" != "arm64" ]]; then
        echo "Warning: This system appears to be $ARCH, not ARM64"
        read -p "Continue anyway? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
fi

# Check for sudo
if [ "$EUID" -ne 0 ]; then
    echo "This script needs to be run with sudo"
    echo "Please run: sudo ./setup_ubuntu.sh"
    exit 1
fi

echo "System: Ubuntu $VERSION_ID on $ARCH"
echo ""

echo "Updating package lists..."
apt update

echo ""
echo "Installing Python and build dependencies..."
apt install -y python3-pip python3-venv python3-full \
    build-essential python3-dev

echo ""
echo "Installing WiFi scanning tools..."
apt install -y wireless-tools aircrack-ng iw net-tools \
    wpasupplicant network-manager

echo ""
echo "Installing Bluetooth tools..."
apt install -y bluetooth bluez bluez-tools

echo ""
echo "Installing network libraries..."
apt install -y libpcap-dev libglib2.0-dev libbluetooth-dev

echo ""
echo "Configuring Bluetooth service..."
systemctl enable bluetooth
systemctl start bluetooth

echo ""
echo "======================================"
echo "Configuring Node Settings..."
echo "======================================"

# Get the real user (before sudo)
REAL_USER=${SUDO_USER:-$USER}
REAL_HOME=$(eval echo ~$REAL_USER)

# Determine project directory
if [ -d "/home/runner/work/dendron/dendron" ]; then
    PROJECT_DIR="/home/runner/work/dendron/dendron"
elif [ -d "$REAL_HOME/dendron" ]; then
    PROJECT_DIR="$REAL_HOME/dendron"
else
    # Try to find it
    PROJECT_DIR=$(cd "$(dirname "$0")/.." && pwd)
fi

CONFIG_FILE="$PROJECT_DIR/configs/node${NODE_NUM}_config.yml"

# Check if config file exists, if not create from template
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Creating config file: $CONFIG_FILE"
    mkdir -p "$PROJECT_DIR/configs"
    
    # Create config file
    cat > "$CONFIG_FILE" << EOF
# Configuration for Scanner Node $NODE_NUM
# Auto-generated by setup script

node_id: "node_${NODE_NUM}"

# Position in meters (x, y, z)
# Adjust these based on your actual room layout
position:
  x: 0      # Adjust X coordinate
  y: 0      # Adjust Y coordinate
  z: 1.5    # Height of Raspberry Pi (meters)

# Server connection
server_url: "http://${SERVER_IP}:5000"

# WiFi interface to use for scanning
wifi_interface: "wlan0"

# How often to scan (seconds)
scan_interval: 5

# Anonymize MAC addresses for privacy (true/false)
anonymize_mac: false
EOF
    
    chown $REAL_USER:$REAL_USER "$CONFIG_FILE"
    echo "✓ Created and configured: $CONFIG_FILE"
else
    # Update existing config file with new server IP
    echo "Updating existing config file: $CONFIG_FILE"
    sed -i "s|server_url:.*|server_url: \"http://${SERVER_IP}:5000\"|" "$CONFIG_FILE"
    echo "✓ Updated server_url in: $CONFIG_FILE"
fi

echo ""
echo "======================================"
echo "Setup Complete!"
echo "======================================"
echo ""
echo "System Information:"
echo "  OS: Ubuntu $VERSION_ID"
echo "  Architecture: $ARCH"
echo "  Python: $(python3 --version)"
echo ""
echo "Configuration:"
echo "  Node Number: $NODE_NUM"
echo "  Server URL: http://${SERVER_IP}:5000"
echo "  Config File: $CONFIG_FILE"
echo ""

if [[ "$IS_SERVER_NODE" == "true" ]]; then
    echo "Next steps for SERVER + CLIENT setup:"
    echo "1. Install server dependencies: sudo ./scripts/setup_server.sh"
    echo "2. Start both: sudo ./scripts/start_server_and_node.sh $CONFIG_FILE"
else
    echo "Next steps for CLIENT ONLY setup:"
    echo "1. Ensure server is running on $SERVER_IP"
    echo "2. Adjust position coordinates in: $CONFIG_FILE"
    echo "3. Start client: sudo ./scripts/start_node${NODE_NUM}.sh"
fi

echo ""
echo "Note: You may need to reboot for all changes to take effect"
echo ""
